pipeline {
    agent { label 'docker' }
        stages {
            stage('Run docker') {
            steps {
                container('docker'){
                    sh """
                        cat /etc/os-release;
                        ls -lah;
                        cd vote;
                        buildctl build --frontend dockerfile.v0 --local context=. --local dockerfile=. --output type=image,name=vote,push=true
                    """
                }
                
            }
        }
    }
}

