pipeline {
    agent { label 'docker' }
        stages {
            stage('Run docker') {
            steps {
                container('docker'){
                    privileged true
                    sh """
                        cat /etc/os-release;
                        ls -lah;
                        cd vote;
                        which docker;
                    """
                }
                
            }
        }
    }
}

